include(ExternalProject)

set(DEPENDENCY_NAME "async-mqtt5")

message("Configuring External Dependency: ${DEPENDENCY_NAME}")

set(ASYNC_MQTT5_GIT_URL "https://github.com/mireo/async-mqtt5.git")
set(ASYNC_MQTT5_GIT_TAG "${SPECTRE_ASYNC_MQTT5_VERSION}")

message(STATUS "ASYNC_MQTT5_GIT_TAG: ${ASYNC_MQTT5_GIT_TAG}")

set(ASYNC_MQTT5_PREFIX_DIR)
if (WIN32)
  set(ASYNC_MQTT5_PREFIX_DIR ${SPECTRE_DEPENDENCIES_INSTALL_DIR}\\${DEPENDENCY_NAME})
else()
  set(ASYNC_MQTT5_PREFIX_DIR ${SPECTRE_DEPENDENCIES_INSTALL_DIR}/${DEPENDENCY_NAME})
endif()

ExternalProject_Add( ${DEPENDENCY_NAME}
  PREFIX         ${ASYNC_MQTT5_PREFIX_DIR}

  # This depend on boost and openssl ExternalProject target
  DEPENDS       boost openssl

  GIT_REPOSITORY ${ASYNC_MQTT5_GIT_URL}
  GIT_TAG        ${ASYNC_MQTT5_GIT_TAG}
  GIT_PROGRESS   TRUE
  GIT_SHALLOW    TRUE

  USES_TERMINAL_DOWNLOAD TRUE

  TEST_COMMAND ""
  UPDATE_COMMAND ""
  PATCH_COMMAND ""

  CMAKE_ARGS
    -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -D CMAKE_INSTALL_PREFIX=${ASYNC_MQTT5_PREFIX_DIR}
    -D BUILD_SHARED_LIBS=OFF
    -D BUILD_EXAMPLES=OFF
    -D CMAKE_EXE_LINKER_FLAGS="-pthread"
    -D CMAKE_CXX_FLAGS="-pthread"
    -D CMAKE_C_FLAGS="-pthread"
    -D Boost_INCLUDE_DIR=${BOOST_PREFIX_DIR}/include
    -D async-mqtt5_INSTALL_CMAKEDIR=${ASYNC_MQTT5_PREFIX_DIR}/lib/cmake/async-mqtt5
    -D CMAKE_INSTALL_INCLUDEDIR=${ASYNC_MQTT5_PREFIX_DIR}/include
    -D CMAKE_INSTALL_LIBDIR=${ASYNC_MQTT5_PREFIX_DIR}/lib
)

set(SPECTRE_DEPENDENCY_ASYNC_MQTT5_INSTALL_DIR ${ASYNC_MQTT5_PREFIX_DIR} CACHE INTERNAL "async-mqtt5 Install Directory")

message("Configuring External Dependency: ${DEPENDENCY_NAME} - DONE")
