include(ExternalProject)

set(DEPENDENCY_NAME "opencv")

message("Configuring External Dependency: ${DEPENDENCY_NAME}")

set(OPENCV_GIT_URL "https://github.com/opencv/opencv.git")
set(OPENCV_GIT_TAG "${SPECTRE_OPENCV_VERSION}")

set(OPENCV_PREFIX_DIR)
if (WIN32)
  set(OPENCV_PREFIX_DIR ${SPECTRE_DEPENDENCIES_INSTALL_DIR}\\${DEPENDENCY_NAME})
else()
  set(OPENCV_PREFIX_DIR ${SPECTRE_DEPENDENCIES_INSTALL_DIR}/${DEPENDENCY_NAME})
endif()

ExternalProject_Add( ${DEPENDENCY_NAME}
  PREFIX         ${OPENCV_PREFIX_DIR}

  GIT_REPOSITORY ${OPENCV_GIT_URL}
  GIT_TAG        ${OPENCV_GIT_TAG}
  GIT_PROGRESS   TRUE
  GIT_SHALLOW    TRUE

  USES_TERMINAL_DOWNLOAD TRUE

  TEST_COMMAND ""
  UPDATE_COMMAND ""
  PATCH_COMMAND ""

  CMAKE_ARGS
    -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -D CMAKE_INSTALL_PREFIX=${OPENCV_PREFIX_DIR}
    -D BUILD_SHARED_LIBS=OFF
    -D BUILD_DOCS=OFF
    -D BUILD_TESTS=OFF
    -D BUILD_PERF_TESTS=OFF
    -D BUILD_EXAMPLES=OFF
    -D BUILD_JAVA=OFF
    -D OPENCV_FORCE_3RDPARTY_BUILD=ON
    -D OPENCV_IPP_ENABLE_ALL=ON
    -D WITH_CAROTENE=ON
    -D WITH_KLEIDICV=ON
    -D WITH_CPUFEATURES=ON
    -D WITH_EIGEN=OFF
    -D WITH_OPENVX=ON
    -D WITH_DIRECTX=ON
    -D WITH_VA=ON
    -D WITH_LAPACK=ON
    -D WITH_QUIRC=ON
    -D BUILD_ZLIB=ON
    -D BUILD_ITT=ON
    -D WITH_IPP=OFF
    -D BUILD_IPP_IW=ON
)

# set(OPENCV_INCLUDE_DIRS ${OPENCV_PREFIX_DIR}/include/opencv4)
set(OpenCV_DIR ${OPENCV_PREFIX_DIR}/lib/cmake/opencv4)

set(SPECTRE_DEPENDENCY_OPENCV_INSTALL_DIR ${OPENCV_PREFIX_DIR} CACHE PATH "OpenCV install directory")

message("Configuring External Dependency: ${DEPENDENCY_NAME} - DONE")
